import express from "express";
import homeController from "../controllers/homeController";
import userController from "../controllers/userController";
//import userController from "../controllers/userController";
let router = express.Router();
let initWebRoutes = (app) => {
  // router.get("/", homeController.getHomePage);
  // router.get("/crud", homeController.fillCRUD);
  // router.post("/post-crud", homeController.postCRUD);
  // router.get("/edit-crud", homeController.getEditCRUD);
  // router.post("/put-crud", homeController.putCRUD);
  // router.get("/delete-crud", homeController.deleteCRUD);
  // router.post("/api/login", userController.handleLogin);
  // router.get("/api/get-all-users", userController.handleGetAllUsers);
  // router.post("/api/create-new-user", userController.handleCreateNewUser);
  // router.put("/api/edit-user", userController.handleEditUser);
  // router.delete("/api/delete-user", userController.handleDeleteUser);
  router.get("/", homeController.getHomePage);
  //router.get("/create-a-user", homeController.createNewUser);
  router.get("/create-a-staff", homeController.createNewStaff);
  router.get("/create-a-book", homeController.createNewBook);
  router.get("/api/get-all-books", userController.handleGetAllBooks);
  router.post("/api/login", userController.handleLogin);
  return app.use("/", router);
};
module.exports = initWebRoutes;
